Repository nyancodeid/quotes, pull requests merged in 2021-10, with the labels that each got.

#2 Add quotes from Ali bin Abi Thali, Ibnu Atha’illah, and Imam Syafi'i
  quotes/azizramdan.yaml
Labels: enhancement

#10 added quotes from william tanuwijaya
  quotes/akrindev.yaml
Labels: enhancement

#35 Add Quotes by jerome polin
  quotes/fitri.yaml
Labels: enhancement, hacktoberfest-accepted

#44 Quotes by Habib Husein Ja'far
  quotes/ayatullahnaufal.yaml
Labels: invalid

#60 feat: ssg, infinite scroll, and more
  .env
  .gitignore
  package-lock.json
  package.json
  quotes/generator.js
  src/components/Dialog.vue
  src/components/QuoteCard.vue
  src/components/QuoteGallery.vue
  src/main.ts
  src/types.d.ts
  src/utils/helpers.ts
  tsconfig.json
  vite.config.ts
Labels: enhancement, hacktoberfest-accepted

#96 Feat Quotes: add new quotes nyancodeid
  quotes/IlhamSetiawan.yaml
  quotes/nyancodeid.yaml
Labels: auto-merge

#94 quotes about fishing add
  quotes/harisetyopermadi.yml
Labels: enhancement, hacktoberfest-accepted, auto-merge

#98 ilhamhzrd20
  quotes/ilhamhzrd20.yaml
Labels: enhancement, hacktoberfest-accepted, auto-merge

#99 Create Iyansr.yaml
  quotes/Iyansr.yaml
Labels: enhancement, hacktoberfest-accepted, auto-merge

#87 Add quotes from dyvue
  quotes/dyvue.yaml
Labels: enhancement, hacktoberfest-accepted, auto-merge

#100 add quote by Ibrohim
  quotes/blackinitial.yaml
Labels: enhancement, hacktoberfest-accepted, auto-merge

#102 add quote by agustacandi
  quotes/agustacandi.yaml
Labels: enhancement, hacktoberfest-accepted, auto-merge

#105 Add: new quote from MaxdhaMax
  quotes/MaxdhaMax.yaml
Labels: enhancement, hacktoberfest-accepted, auto-merge

#107 Add quotes by medival
  quotes/medival.yaml
Labels: enhancement, hacktoberfest-accepted, auto-merge

#109 Add quote by hsiav4
  quotes/hsiav4.yaml
Labels: enhancement, auto-merge

#289 add new quotes
  quotes/fadzrinmadu.yaml
Labels: hacktoberfest-accepted, auto-merge, submit-quotes

#290 Adding new quotes!
  quotes/ralphie97.yaml
Labels: hacktoberfest-accepted, auto-merge, submit-quotes

#266 Create NATSU03.yaml
  quotes/NATSU03.yaml
Labels: hacktoberfest-accepted, auto-merge, submit-quotes

#273 Create reingxd.yaml
  quotes/reingxd.yaml
Labels: hacktoberfest-accepted, auto-merge, submit-quotes

#288 Added new File
  quotes/Vaibhavwani11.yaml
Labels: hacktoberfest-accepted, auto-merge, submit-quotes

#292 feat(quotes): update quote from Gus Dur
  quotes/fariqfgi.yaml
Labels: hacktoberfest-accepted, auto-merge, submit-quotes

#293 add new quotes
  quotes/fadzrinmadu.yaml
Labels: hacktoberfest-accepted, auto-merge, submit-quotes

#296 Add quotes
  quotes/licensed.yaml
Labels: hacktoberfest-accepted, auto-merge, submit-quotes
